theme: jekyll-theme-cayman
lang: en
url: https://live.code-maven.com
baseurl: ""
title: "Code-Maven community online events"
description: Virtual presentations, workshops, Zoominars, online conversations
show_downloads: false

plugins:
   - jekyll-seo-tag

nav_links:
   - label: Upcoming and Recordings
     url: /
   - label: Telegram
     url: /telegram
   - label: LinkedIn
     url: /linkedin
   - label: About
     url: /about

calendars:
   - label: Python
     url: https://luma.com/python-maven
   - label: Rust
     url: https://luma.com/rust-maven
   - label: Perl
     url: https://luma.com/perl-maven
   - label: Git
     url: https://luma.com/git-maven
   - label: Databases
     url: https://luma.com/db-maven
   - label: AI
     url: https://luma.com/ai-maven
   - label: Everything
     url: https://luma.com/code-maven

telegram_links:
   - label: Python Maven
     url: https://t.me/PythonMaven
   - label: Rust Maven
     url: https://t.me/RustMaven
   - label: Perl Maven
     url: https://t.me/PerlMaven
   - label: Code Maven community
     url: https://t.me/Code_Mavens

linkedin:
    - label: Gabor Szabo
      url: https://www.linkedin.com/in/szabgab/
    - label: Python Maven
      url: https://www.linkedin.com/showcase/python-maven/?viewAsMember=true
    - label: Perl Maven
      url: https://www.linkedin.com/showcase/perl-maven/?viewAsMember=true
    - label: Code Maven
      url: https://www.linkedin.com/company/code-maven-world/?viewAsMember=true
    - label: DevOps Maven
      url: https://www.linkedin.com/showcase/devops-maven/?viewAsMember=true
    - label: Go Maven
      url: https://www.linkedin.com/showcase/go-maven/about/?viewAsMember=true
    - label: Rust Maven
      url: https://www.linkedin.com/showcase/rust-maven/?viewAsMember=true

github:
   is_project_page: false
