theme: jekyll-theme-cayman
lang: en
url: https://live.code-maven.com
baseurl: ""
title: "Code-Maven Live events"
description: Virtual presentations, Zoominars
show_downloads: false

plugins:
   - jekyll-seo-tag

nav_links:
   - label: Upcoming and Recordings
      url: /
   - label: About
      url: /about
   - label: Earlier Events
      url: /old

quick_links:
   - label: Python Calendar
      url: https://luma.com/python-maven
   - label: Rust Calendar
      url: https://luma.com/rust-maven
   - label: Perl Calendar
      url: https://luma.com/perl-maven
   - label: Code Maven Calendar
      url: https://luma.com/code-maven

github:
   is_project_page: false
