theme: jekyll-theme-cayman
lang: en
url: https://live.code-maven.com
baseurl: ""
title: "Code-Maven Live events"
description: Virtual presentations, workshops, Zoominars
show_downloads: false

plugins:
   - jekyll-seo-tag

nav_links:
   - label: Upcoming and Recordings
     url: /
   - label: About
     url: /about
   - label: Earlier Events
     url: /old

calendars:
   - label: Python
     url: https://luma.com/python-maven
   - label: Rust
     url: https://luma.com/rust-maven
   - label: Perl
     url: https://luma.com/perl-maven
   - label: Git[Hub|Lab]
     url: https://luma.com/git-maven
   - label: Databases
     url: https://luma.com/db-maven
   - label: Code Maven
     url: https://luma.com/code-maven

telegram_links:
   - label: Python Maven
     url: https://t.me/PythonMaven
   - label: Rust Maven
     url: https://t.me/RustMaven
   - label: Perl Maven
     url: https://t.me/PerlMaven
   - label: Code Maven community
     url: https://t.me/Code_Mavens

github:
   is_project_page: false
